---
title: "Run Model"
author: "Carys Jones"
date: '2023-02-01'
output: html_document
---


# Dependencies
```{r}
box::use(.. / R / dirs[dirs])
box::use(clean = ../ R / clean_data)
box::use(mod = ../ R / for_models)


box::use(readr[read_csv])
box::use(ggplot2[...])
box::use(dplyr)
box::use(moments)
box::use(kinship2)
box::use(sf)
box::use(tidyr)
box::use(pedantics)
box::use(magrittr[`%>%`])
box::use(asreml)
box::use(tibble)


```



OUTPUT

```{r}


# Results LD --------------------------------------------------------------


LD_basic <- readRDS('./output/AnMod_test_basic_FINAL.rds')
LD_NB <- readRDS('./output/AnMod_test_NB_FINAL.rds')
LD_envir <- readRDS('./output/AnMod_test_envir_FINAL.rds')
LD_dist <- readRDS('./output/AnMod_test_dist_FINAL.rds')

summary(LD_basic)$varcomp
summary(LD_NB)$varcomp
summary(LD_dist)$varcomp
summary(LD_envir)$varcomp
summary(LD_dist_env2)$varcomp


#make to little tables of raw var comps
LD_basic_varcomp <- summary(LD_basic)$varcomp
LD_basic_varcomp <- rownames_to_column(LD_basic_varcomp, var = "comp")
LD_basic_varcomp$model <- 'model 1'

LD_NB_varcomp <- summary(LD_NB)$varcomp
LD_NB_varcomp <- rownames_to_column(LD_NB_varcomp, var = "comp")
LD_NB_varcomp$model <- 'model 2'

LD_dist_varcomp <- summary(LD_dist)$varcomp
LD_dist_varcomp <- rownames_to_column(LD_dist_varcomp, var = "comp")
LD_dist_varcomp$model <- 'model 3'

LD_envir_varcomp <- summary(LD_envir)$varcomp
LD_envir_varcomp <- rownames_to_column(LD_envir_varcomp, var = "comp")
LD_envir_varcomp$model <- 'model 4'

#combine
varcomp_comb <- rbind(LD_basic_varcomp, LD_NB_varcomp, LD_dist_varcomp, LD_envir_varcomp)

#fixed effects
summary(LD_basic, coef = T)$coef.fixed
summary(LD_NB, coef = T)$coef.fixed
summary(LD_dist, coef = T)$coef.fixed
summary(LD_envir, coef = T)$coef.fixed

#wald tests
# wald(LD_dist, denDF = "default", ssType = "conditional")$Wald
# wald.asreml(LD_dist_env, ssType = "conditional", denDF = "numeric")  # P-value for fixed effects


# outputs -----------------------------------------------------------------



#AIC
LD_basic_AIC <- LD_basic$loglik
LD_NB_AIC <- LD_NB$loglik
LD_dist_AIC <- LD_dist$loglik
LD_envir_AIC <- LD_envir$loglik

#total phenotypic variance
LD_basic.VPtot <- vpredict(LD_basic, LD_basic.VPtot ~ V1 + V2 + V3 + V4)
LD_NB.VPtot <- vpredict(LD_NB, LD_NB.VPtot ~ V1 + V2 + V3 + V4 + V5)
LD_dist.VPtot <- vpredict(LD_dist, LD_dist.VPtot ~ V1 + V2 + V3 + V4 + V5)
LD_envir.VPtot <- vpredict(LD_envir, LD_envir.VPtot ~ V1 + V2 + V3 + V4 + V5)

#total phenotypic variance within year
LD_basic.VP <- vpredict(LD_basic, LD_basic.VP ~  V2 + V3 + V4)
LD_NB.VP <- vpredict(LD_NB, LD_NB.VP ~ V2 + V3 + V4 + V5)
LD_dist.VP <- vpredict(LD_dist, LD_dist_test.VP ~ V2 + V3 + V4 + V5)
LD_envir.VP <- vpredict(LD_envir, LD_envir.VP ~ V2 + V3 + V4 + V5)

#heritability - total
LD_basic.h2 <- vpredict(LD_basic, LD_basic.h2 ~ V2 / (V2 + V3 + V4))
LD_NB.h2 <- vpredict(LD_NB, LD_NB.h2 ~ V3 / (V2 + V3 + V4 + V5))
LD_dist.h2 <- vpredict(LD_dist, LD_dist.h2 ~ V3 / (V2 + V3 + V4 + V5))
LD_envir.h2 <- vpredict(LD_envir, LD_envir.h2 ~ V3 / (V2 + V3 + V4 + V5))

#heritability - within-year
LD_basic.h2tot <- vpredict(LD_basic, LD_basic.h2tot ~ V2 / (V1 + V2 + V3 + V4))
LD_NB.h2tot <- vpredict(LD_NB, LD_NB.h2tot ~ V3 / (V1 + V2 + V3 + V4 + V5))
LD_dist.h2tot <- vpredict(LD_dist, LD_dist.h2tot ~ V3 / (V1 + V2 + V3 + V4 + V5))
LD_envir.h2tot <- vpredict(LD_envir, LD_envir.h2tot ~ V3 / (V1 + V2 + V3 + V4 + V5))


#prop explained by NB, and matrices within year
LD_NB.SPACEprop <- vpredict(LD_NB, LD_NB.SPACEprop ~ V2 / (V2 + V3 + V4 + V5))
LD_dist.SPACEprop <- vpredict(LD_dist, LD_dist.SPACEprop ~ V2 / (V2 + V3 + V4 + V5))
LD_envir.SPACEprop <- vpredict(LD_envir, LD_envir.SPACEprop ~ V2 / (V2 + V3 + V4 + V5))


#get prop explained by each var comp
#breed year
LD_basic.BY <- vpredict(LD_basic, BY ~ V1)
LD_NB.BY <- vpredict(LD_NB, BY ~ V1)
LD_dist.BY <- vpredict(LD_dist, BY ~ V1)
LD_envir.BY <- vpredict(LD_envir, BY ~ V1)
#mother vm
LD_basic.VM <- vpredict(LD_basic, VM ~ V2 )
LD_NB.VM <- vpredict(LD_NB, VM ~ V3 )
LD_dist.VM <- vpredict(LD_dist, VM ~ V3 )
LD_envir.VM <- vpredict(LD_envir, VM ~ V3 )
#mother ide
LD_basic.IDE <- vpredict(LD_basic, IDE ~ V3)
LD_NB.IDE <- vpredict(LD_NB, IDE ~ V4)
LD_dist.IDE <- vpredict(LD_dist, IDE ~ V4)
LD_envir.IDE <- vpredict(LD_envir, IDE ~ V4)
#residuls
LD_basic.R <- vpredict(LD_basic, R ~ V4)
LD_NB.R <- vpredict(LD_NB, R ~ V5)
LD_dist.R <- vpredict(LD_dist, R ~ V5)
LD_envir.R <- vpredict(LD_envir, R ~ V5)
#matrix
LD_basic.NONE <- 0
LD_NB.NB <- vpredict(LD_NB, NB ~ V2)
LD_dist.DIST <- vpredict(LD_dist, DIST ~ V2)
LD_envir.ENVIR <- vpredict(LD_envir, ENVIR ~ V2)


#test model signif
#
2*(LD_dist$loglik-LD_NB$loglik)
1-pchisq(2*(LD_dist$loglik-LD_NB$loglik),1)

#
2*(LD_dist$loglik-LD_envir$loglik)
1-pchisq(2*(LD_dist$loglik-LD_envir$loglik),1)

#
2*(LD_envir$loglik-LD_NB$loglik)
1-pchisq(2*(LD_envir$loglik-LD_NB$loglik),1)





# var comp  ---------------------------------------------------------------



library(tibble)
#combine
basic_comb <- rbind(LD_basic.BY, 
                    LD_basic.VM,
                    LD_basic.IDE, 
                    LD_basic.R
)

basic_comb <- rownames_to_column(basic_comb, var = "variable")
basic_comb$model <- 'model 1'
basic_comb$prop <- basic_comb$Estimate / sum(basic_comb$Estimate)
basic_comb$propSE <- (basic_comb$SE / basic_comb$Estimate) * basic_comb$prop
#basic_comb$prop_and_SE <- paste(basic_comb$prop, '(', basic_comb$propSE, ')')


NB_comb <- rbind(LD_NB.BY, 
                 LD_NB.VM,
                 LD_NB.IDE, 
                 LD_NB.R,
                 LD_NB.NB
)

NB_comb <- rownames_to_column(NB_comb, var = "variable")
NB_comb$model <- 'model 2'
NB_comb$prop <- NB_comb$Estimate / sum(NB_comb$Estimate)
NB_comb$propSE <- (NB_comb$SE / NB_comb$Estimate) * NB_comb$prop



dist_comb <- rbind(LD_dist.BY, 
                   LD_dist.VM,
                   LD_dist.IDE, 
                   LD_dist.R,
                   LD_dist.DIST
)

dist_comb <- rownames_to_column(dist_comb, var = "variable")
dist_comb$model <- 'model 3'
dist_comb$prop <- dist_comb$Estimate / sum(dist_comb$Estimate)
dist_comb$propSE <- (dist_comb$SE / dist_comb$Estimate) * dist_comb$prop



envir_comb <- rbind(LD_envir.BY, 
                    LD_envir.VM,
                    LD_envir.IDE, 
                    LD_envir.R,
                    LD_envir.ENVIR
)

envir_comb <- rownames_to_column(envir_comb, var = "variable")
envir_comb$model <- 'model 4'
envir_comb$prop <- envir_comb$Estimate / sum(envir_comb$Estimate)
envir_comb$propSE <- (envir_comb$SE / envir_comb$Estimate) * envir_comb$prop


nrow(basic_comb)
nrow(NB_comb)
nrow(dist_comb)
nrow(envir_comb)


all_comb <- rbind(basic_comb, NB_comb, dist_comb, envir_comb)

var_comp <- ggplot(all_comb, aes(x = model, y = prop, fill = variable)) +
  geom_col(position = 'stack') + 
  ylab('Proportion of variance') + xlab(label = '') +
  scale_fill_manual(values=c("#43BB99", "#99DDFE", "#FEAABB",
                             "#EEDD88", "#EE8866", "#77AADE", 'dark grey')) +
  theme(
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    plot.background = ggplot2::element_rect(fill = 'transparent'), 
    panel.background = ggplot2::element_rect(fill = 'transparent'))


ggsave(
  filename = "var_comp.png",
  plot = var_comp,
  scale = 1,
  width = 14,
  height = 18,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)


#FOR POSTER

#change name of NB, DIST and ENV to be same
all_comb$variable[all_comb$variable == 'NB'] <- 'RAND'
all_comb$variable[all_comb$variable == 'DIST'] <- 'RAND'
all_comb$variable[all_comb$variable == 'ENVIR'] <- 'RAND'

#reorder 
all_comb <- all_comb %>% 
  mutate(variable2 = factor(variable, levels = c("RAND", "IDE", "VM", "BY", "R")))

var_comp_poster <- ggplot(all_comb, aes(x = model, y = prop, fill = variable2)) +
  geom_col(position = 'stack') + 
  ylab('Proportion of variance') + xlab(label = '') +
  scale_fill_manual(values=c("#79B0CD", "#FEAABB", "#EEDD88", "#43BB99", "#EE8866")) +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent'), #transparent legend panel
    # panel.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
    # plot.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
    # panel.grid.major.x = element_blank(),
    # panel.grid.minor.x = element_blank(),
    # panel.grid.minor.y = element_blank(),
    # panel.grid.major.y = element_blank(),
    #axis.title.x = element_text(colour = "#a4948c"),
    text = element_text(color="#2F5597", face = 'bold', size = 16), 
    axis.text = element_text(color="#2F5597", face = 'bold', size = 10),
    #axis.title.y = element_blank(),
   # panel.border=element_blank(),
    #plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    legend.position = 'none')
var_comp_poster


ggsave(
  filename = "./plots/poster_var_comp_transp_2.png",
  plot = var_comp_poster,
  scale = 1,
  width = 10.5,
  height = 17.25,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)



# herit -------------------------------------------------------------------


#plot heritability

herit <- rbind(LD_basic.h2, LD_NB.h2, LD_dist.h2, LD_envir.h2)
herit <- rownames_to_column(herit, var = "model")
herit$model2 <- c('Basic model', 'Nestbox model', 'Spatial matrix', 'Environment matrix')

herit$model2 = factor(herit$model2, levels = c('Environment matrix', 'Spatial matrix', 
                                               'Nestbox model', 'Basic model'))


herit_plot <- ggplot(herit, aes(x = model2, y = Estimate)) +
  geom_errorbar(aes(ymin = Estimate - SE, ymax = Estimate + SE), width = 0.2) +
  geom_point(colour = '#77AADE', size = 10) + 
  scale_size_area(max_size = 1) +
  theme_bw() + coord_flip() +
  ylab('Within-year heritability') +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent'), #transparent legend panel
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
  )

herit_plot

ggsave(
  filename = "herit_plot_transp.png",
  plot = herit_plot,
  scale = 1,
  width = 20,
  height = 5,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)



##HERIT FOR POSTER

herit_plot_poster <- ggplot(herit, aes(y = model2, x = Estimate)) +
  geom_col(fill = '#EEDD88') + 
  geom_errorbar(aes(xmin = Estimate - SE, xmax = Estimate + SE), colour = '#C0B26E', width = 0.2) +
  xlab('Within-year heritability (SE)') + ylab('') +
  theme(panel.background = element_rect(fill='transparent'), #transparent panel bg
        plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
        panel.grid.major = element_blank(), #remove major gridlines
        panel.grid.minor = element_blank(), #remove minor gridlines
        legend.background = element_rect(fill='transparent'), #transparent legend bg
        legend.box.background = element_rect(fill='transparent'), #transparent legend panel
        # panel.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
        # plot.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
        # panel.grid.major.x = element_blank(),
        # panel.grid.minor.x = element_blank(),
        # panel.grid.minor.y = element_blank(),
        # panel.grid.major.y = element_blank(),
        #axis.title.x = element_text(colour = "#a4948c"),
        #axis.title.y = element_text(colour = "#a4948c"),
        text = element_text(color="#2F5597", face = 'bold', size = 14), 
        axis.text = element_text(color="#2F5597", face = 'bold', size = 10))

plot(herit$Estimate)

herit_plot_poster

ggsave(
  filename = "./plots/herit_plot_poster_transp.png",
  plot = herit_plot_poster,
  scale = 1,
  width = 22,
  height = 9,
  units = "cm",
  dpi = 350,
  limitsize = FALSE
)


#for paper
herit_plot_paper <- ggplot(herit, aes(y = model2, x = Estimate)) +
  geom_errorbar(aes(xmin = Estimate - SE, xmax = Estimate + SE), width = 0.3, size = 0.7, colour = '#2F5597') +
  geom_point(colour = '#77AADE', size = 6, shape = 18) + 
  scale_size_area(max_size = 1) +
  theme_bw() + #coord_flip() +
  xlab("Within-year heritability") +
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major.y = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent'), #transparent legend panel
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    axis.ticks=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    #axis.title.x = element_text(colour = "#a4948c"),
    #axis.title.y = element_text(colour = "#a4948c"),
    text = element_text(color="black", face = 'bold', size = 14), 
    axis.text = element_text(color="black", face = 'bold', size = 10))

herit_plot_paper

ggsave(
  filename = "./plots/herit_plot_paper.png",
  plot = herit_plot_paper,
  scale = 1,
  width = 22,
  height = 9,
  units = "cm",
  dpi = 350,
  limitsize = FALSE
)




####FOR POSTER

##ACCOUNTING FOR SPACE
#with and without BY
LD_space <- rbind(LD_NB.SPACEprop,
                  LD_dist.SPACEprop,
                  LD_envir.SPACEprop
)

LD_space <- rownames_to_column(LD_space, var = "model")
LD_space$model_simp <- c( '2', '3', '4')

variance_space <- ggplot(transform(LD_space, model_simp = factor(model_simp, levels=c('4','3','2'))),
       aes(x = Estimate, y = model_simp)) +
  geom_col(fill = "#79B0CD") + 
  geom_errorbar(aes(xmin = Estimate - SE, xmax = Estimate + SE), colour = "#608DA6", width = 0.2) +
  ylab('') + xlab('Proportion within-year variance (SE)') +
  theme(panel.background = element_rect(fill='transparent'), #transparent panel bg
        plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
        panel.grid.major = element_blank(), #remove major gridlines
        panel.grid.minor = element_blank(), #remove minor gridlines
        legend.background = element_rect(fill='transparent'), #transparent legend bg
        legend.box.background = element_rect(fill='transparent'), #transparent legend panel
        # panel.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
        # plot.background = element_rect(fill = "#B4C7E7", color = "#B4C7E7"),
        # panel.grid.major.x = element_blank(),
        # panel.grid.minor.x = element_blank(),
        # panel.grid.minor.y = element_blank(),
        # panel.grid.major.y = element_blank(),
        #axis.title.x = element_text(colour = "#a4948c"),
        #axis.title.y = element_text(colour = "#a4948c"),
        text = element_text(color="#2F5597", face = 'bold', size = 14), 
        axis.text = element_text(color="#2F5597", face = 'bold', size = 10))

variance_space

ggsave(
  filename = "./plots/variance_space_transp_2.png",
  plot = variance_space,
  scale = 1,
  width = 22,
  height = 9,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)












###combine to make table

#empty rows for Nb envir and spatial
env_row <- data.frame('variable' = 'ENV', 'component' = '-', 'std.error' = '-',
                      'prop' = '-', 'propSE' = '-')
dist_row <- data.frame('variable' = 'DIST', 'component' = '-', 'std.error' = '-',
                      'prop' = '-', 'propSE' = '-')
NB_row <- data.frame('variable' = 'NB', 'component' = '-', 'std.error' = '-',
                      'prop' = '-', 'propSE' = '-')

#these have raw values
#LD_basic_varcomp, LD_NB_varcomp, LD_dist_varcomp, LD_envir_varcomp

basic_est <- rbind(cbind(basic_comb[1], LD_basic_varcomp[2], LD_basic_varcomp[3],
      basic_comb[5], basic_comb[6]), NB_row, dist_row, env_row)

NB_est <- rbind(cbind(NB_comb[1], LD_NB_varcomp[2], LD_NB_varcomp[3],
      NB_comb[5], NB_comb[6]), dist_row, env_row)

dist_est <- rbind(cbind(dist_comb[1], LD_dist_varcomp[2], LD_dist_varcomp[3],
      dist_comb[5], dist_comb[6]), NB_row)
#make sure rows in same order as others
dist_est <- dist_est %>% slice(-5) %>% bind_rows(dist_est %>% slice(5))
dist_est <- rbind(dist_est, env_row)

env_est <- rbind(cbind(envir_comb[1], LD_envir_varcomp[2], LD_envir_varcomp[3],
                       envir_comb[5], envir_comb[6]), NB_row, dist_row)
env_est <- env_est %>% slice(-5) %>% bind_rows(env_est %>% slice(5))


#these have proportions
#basic_comb, NB_comb, dist_comb, envir_comb

basic_est2 <- rbind(LD_basic.VPtot, LD_basic.VP, LD_basic.h2tot, LD_basic.h2)
NB_est2 <- rbind(LD_NB.VP, LD_NB.VPtot, LD_NB.h2tot, LD_NB.h2)
dist_est2 <- rbind(LD_dist.VP, LD_dist.VPtot, LD_dist.h2tot, LD_dist.h2)
env_est2 <- rbind(LD_envir.VP, LD_envir.VPtot, LD_envir.h2tot, LD_envir.h2)


#output these 
all_est <- cbind(basic_est, NB_est, dist_est, env_est)
write.csv(all_est, file = './output/AnMod_estimates_varcomps.csv')


all_est2 <- cbind(basic_est2, NB_est2, dist_est2, env_est2)
write.csv(all_est2, file = './output/AnMod_estimates_tots.csv')



# Results HD  -------------------------------------------------------------

HD_basic <- readRDS('./output/AnMod_test_basic_HD_FINAL.rds')
HD_NB <- readRDS('./output/AnMod_test_NB_HD_FINAL.rds')
HD_envir <- readRDS('./output/AnMod_test_envir_HD_FINAL.rds')
HD_dist <- readRDS('./output/AnMod_test_dist_HD_FINAL.rds')

summary(HD_basic)$varcomp
summary(HD_NB)$varcomp
summary(HD_dist)$varcomp
summary(HD_envir)$varcomp

#make to little tables of raw var comps
HD_basic_varcomp <- summary(HD_basic)$varcomp
HD_basic_varcomp <- rownames_to_column(HD_basic_varcomp, var = "comp")
HD_basic_varcomp$model <- 'model 1'

HD_NB_varcomp <- summary(HD_NB)$varcomp
HD_NB_varcomp <- rownames_to_column(HD_NB_varcomp, var = "comp")
HD_NB_varcomp$model <- 'model 2'

HD_dist_varcomp <- summary(HD_dist)$varcomp
HD_dist_varcomp <- rownames_to_column(HD_dist_varcomp, var = "comp")
HD_dist_varcomp$model <- 'model 3'

HD_envir_varcomp <- summary(HD_envir)$varcomp
HD_envir_varcomp <- rownames_to_column(HD_envir_varcomp, var = "comp")
HD_envir_varcomp$model <- 'model 4'

#combine
HD_varcomp_comb <- rbind(HD_basic_varcomp, HD_NB_varcomp, HD_dist_varcomp, HD_envir_varcomp)

#fixed effects
summary(HD_basic, coef = T)$coef.fixed
summary(HD_NB, coef = T)$coef.fixed
summary(HD_dist, coef = T)$coef.fixed
summary(HD_envir, coef = T)$coef.fixed

#AIC
HD_basic_AIC <- HD_basic$loglik
HD_NB_AIC <- HD_NB$loglik
HD_dist_AIC <- HD_dist$loglik
HD_envir_AIC <- HD_envir$loglik

#total phenotypic variance
HD_basic.VP <- vpredict(HD_basic, HD_basic.VP ~ V1 + V2 + V3 + V4)
HD_NB.VP <- vpredict(HD_NB, HD_NB.VP ~ V1 + V2 + V3 + V4 + V5)
HD_dist.VP <- vpredict(HD_dist, HD_dist.VP ~ V1 + V2 + V3 + V4 + V5)
HD_envir.VP <- vpredict(HD_envir, HD_envir.VP ~ V1 + V2 + V3 + V4 + V5)

#total phenotypic variance within year
HD_basic.VPtot <- vpredict(HD_basic, HD_basic.VPtot ~  V2 + V3 + V4)
HD_NB.VPtot <- vpredict(HD_NB, HD_NB.VPtot ~ V2 + V3 + V4 + V5)
HD_dist.VPtot <- vpredict(HD_dist_test, HD_dist_test.VPtot ~ V2 + V3 + V4 + V5)
HD_envir.VPtot <- vpredict(HD_envir, HD_envir.VPtot ~ V2 + V3 + V4 + V5)

#heritability - total
HD_basic.h2tot <- vpredict(HD_basic, HD_basic.h2tot ~ V2 / (V2 + V3 + V4))
HD_NB.h2tot <- vpredict(HD_NB, HD_NB.h2tot ~ V3 / (V2 + V3 + V4 + V5))
HD_dist.h2tot <- vpredict(HD_dist_test, HD_dist_test.h2tot ~ V3 / (V2 + V3 + V4 + V5))
HD_envir.h2tot <- vpredict(HD_envir_test, HD_envir_test.h2tot ~ V3 / (V2 + V3 + V4 + V5))

#heritability - within-year
HD_basic.h2 <- vpredict(HD_basic, HD_basic.h2 ~ V2 / (V1 + V2 + V3 + V4))
HD_NB.h2 <- vpredict(HD_NB, HD_NB.h2 ~ V3 / (V1 + V2 + V3 + V4 + V5))
HD_dist.h2 <- vpredict(HD_dist, HD_dist.h2 ~ V3 / (V1 + V2 + V3 + V4 + V5))
HD_envir.h2 <- vpredict(HD_envir, HD_envir.h2 ~ V3 / (V1 + V2 + V3 + V4 + V5))


#get prop explained by each var comp
#breed year
HD_basic.BY <- vpredict(HD_basic, BY ~ V1)
HD_NB.BY <- vpredict(HD_NB, BY ~ V1)
HD_dist.BY <- vpredict(HD_dist, BY ~ V1)
HD_envir.BY <- vpredict(HD_envir, BY ~ V1)
#mother vm
HD_basic.VM <- vpredict(HD_basic, VM ~ V2 )
HD_NB.VM <- vpredict(HD_NB, VM ~ V3 )
HD_dist.VM <- vpredict(HD_dist, VM ~ V3 )
HD_envir.VM <- vpredict(HD_envir, VM ~ V3 )
#mother ide
HD_basic.IDE <- vpredict(HD_basic, IDE ~ V3)
HD_NB.IDE <- vpredict(HD_NB, IDE ~ V4)
HD_dist.IDE <- vpredict(HD_dist, IDE ~ V4)
HD_envir.IDE <- vpredict(HD_envir, IDE ~ V4)
#residuls
HD_basic.R <- vpredict(HD_basic, R ~ V4)
HD_NB.R <- vpredict(HD_NB, R ~ V5)
HD_dist.R <- vpredict(HD_dist, R ~ V5)
HD_envir.R <- vpredict(HD_envir, R ~ V5)
#matrix
HD_basic.NONE <- 0
HD_NB.NB <- vpredict(HD_NB, NB ~ V2)
HD_dist.DIST <- vpredict(HD_dist, DIST ~ V2)
HD_envir.ENVIR <- vpredict(HD_envir, ENVIR ~ V2)


#test model signif
#
2*(HD_dist$loglik-HD_NB$loglik)
1-pchisq(2*(HD_dist$loglik-HD_NB$loglik),1)

#
2*(HD_dist$loglik-HD_envir$loglik)
1-pchisq(2*(HD_dist$loglik-HD_envir$loglik),1)

#
2*(HD_envir$loglik-HD_NB$loglik)
1-pchisq(2*(HD_envir$loglik-HD_NB$loglik),1)





#combine
HD_basic_comb <- rbind(HD_basic.BY, 
                    HD_basic.VM,
                    HD_basic.IDE, 
                    HD_basic.R
)

HD_basic_comb <- rownames_to_column(HD_basic_comb, var = "variable")
HD_basic_comb$model <- 'model 1'
HD_basic_comb$prop <- HD_basic_comb$Estimate / sum(HD_basic_comb$Estimate)
HD_basic_comb$propSE <- HD_basic_comb$SE / sum(HD_basic_comb$SE)



HD_NB_comb <- rbind(HD_NB.BY, 
                 HD_NB.VM,
                 HD_NB.IDE, 
                 HD_NB.R,
                 HD_NB.NB
)

HD_NB_comb <- rownames_to_column(HD_NB_comb, var = "variable")
HD_NB_comb$model <- 'model 2'
HD_NB_comb$prop <- HD_NB_comb$Estimate / sum(HD_NB_comb$Estimate)
HD_NB_comb$propSE <- HD_NB_comb$SE / sum(HD_NB_comb$SE)



HD_dist_comb <- rbind(HD_dist.BY, 
                   HD_dist.VM,
                   HD_dist.IDE, 
                   HD_dist.R,
                   HD_dist.DIST
)

HD_dist_comb <- rownames_to_column(HD_dist_comb, var = "variable")
HD_dist_comb$model <- 'model 3'
HD_dist_comb$prop <- HD_dist_comb$Estimate / sum(HD_dist_comb$Estimate)
HD_dist_comb$propSE <- HD_dist_comb$SE / sum(HD_dist_comb$SE)


HD_envir_comb <- rbind(HD_envir.BY, 
                    HD_envir.VM,
                    HD_envir.IDE, 
                    HD_envir.R,
                    HD_envir.ENVIR
)

HD_envir_comb <- rownames_to_column(HD_envir_comb, var = "variable")
HD_envir_comb$model <- 'model 4'
HD_envir_comb$prop <- HD_envir_comb$Estimate / sum(HD_envir_comb$Estimate)
HD_envir_comb$propSE <- HD_envir_comb$SE / sum(HD_envir_comb$SE)


HD_all_comb <- rbind(HD_basic_comb, HD_NB_comb, HD_dist_comb, HD_envir_comb)

#plot variance componenets
# all_comb$model = factor(all_comb$model, levels = c('HD_basic', 'HD_NB', 'HD_dist', 'HD_envir'))
HD_var_comp <- ggplot(HD_all_comb, aes(x = model, y = prop, fill = variable)) +
  geom_col(position = 'stack') + 
  ylab('Proportion of variance') + xlab(label = '') +
  scale_fill_manual(values=c("#43BB99", "#99DDFE", "#FEAABB",
                             "#EEDD88", "#EE8866", "#77AADE", 'dark grey')) +
  theme(
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    plot.background =
      ggplot2::element_rect(fill = 'transparent'),
    panel.background =
      ggplot2::element_rect(fill = 'transparent')
  )

ggsave(
  filename = "var_comp_HD.png",
  plot = HD_var_comp,
  scale = 1,
  width = 14,
  height = 18,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)

#plot heritability

HD_herit <- rbind(HD_basic.h2, HD_NB.h2, HD_dist.h2, HD_envir.h2)
HD_herit <- rownames_to_column(HD_herit, var = "model")
HD_herit$model2 <- c('model 1', 'model 2', 'model 3', 'model 4')

HD_herit$model2 = factor(HD_herit$model2, levels = c('model 4', 'model 3', 
                                               'model 2', 'model 1'))
HD_herit_plot <- ggplot(HD_herit, aes(x = model2, y = Estimate)) +
  geom_col(fill = '#77AADE') + 
  geom_errorbar(aes(ymin = Estimate - SE, ymax = Estimate + SE)) +
  theme_bw() + coord_flip() +
  ylab('Within-year heritability') +
  theme(
    axis.title.y = element_blank(),
    panel.border=element_blank(),
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.margin = unit(c(.8, .8, .8, .8), "cm"),
    plot.background =
      ggplot2::element_rect(fill = 'transparent'),
    panel.background =
      ggplot2::element_rect(fill = 'transparent')
  )

ggsave(
  filename = "herit_plot_HD.png",
  plot = HD_herit_plot,
  scale = 1,
  width = 20,
  height = 5,
  units = "cm",
  dpi = 350,
  limitsize = FALSE,
  bg = "transparent"
)




###combine to make table

#empty rows for Nb envir and spatial
HD_env_row <- data.frame('variable' = 'ENV', 'component' = '-', 'std.error' = '-',
                      'prop' = '-', 'propSE' = '-')
HD_dist_row <- data.frame('variable' = 'DIST', 'component' = '-', 'std.error' = '-',
                       'prop' = '-', 'propSE' = '-')
HD_NB_row <- data.frame('variable' = 'NB', 'component' = '-', 'std.error' = '-',
                     'prop' = '-', 'propSE' = '-')

#these have raw values
#HD_basic_varcomp, HD_NB_varcomp, HD_dist_varcomp, HD_envir_varcomp

HD_basic_est <- rbind(cbind(HD_basic_comb[1], HD_basic_varcomp[2], HD_basic_varcomp[3],
                            HD_basic_comb[5], HD_basic_comb[6]), HD_NB_row, HD_dist_row, HD_env_row)

HD_NB_est <- rbind(cbind(HD_NB_comb[1], HD_NB_varcomp[2], HD_NB_varcomp[3],
                         HD_NB_comb[5], HD_NB_comb[6]), HD_dist_row, HD_env_row)

HD_dist_est <- rbind(cbind(HD_dist_comb[1], HD_dist_varcomp[2], HD_dist_varcomp[3],
                           HD_dist_comb[5], HD_dist_comb[6]), HD_NB_row)
#make sure rows in same order as others
HD_dist_est <- HD_dist_est %>% slice(-5) %>% bind_rows(HD_dist_est %>% slice(5))
HD_dist_est <- rbind(HD_dist_est, HD_env_row)

HD_env_est <- rbind(cbind(HD_envir_comb[1], HD_envir_varcomp[2], HD_envir_varcomp[3],
                          HD_envir_comb[5], HD_envir_comb[6]), HD_NB_row, HD_dist_row)
HD_env_est <- HD_env_est %>% slice(-5) %>% bind_rows(HD_env_est %>% slice(5))


#these have proportions
#basic_comb, NB_comb, dist_comb, envir_comb

HD_basic_est2 <- rbind(HD_basic.VPtot, HD_basic.VP, HD_basic.h2tot, HD_basic.h2)
HD_NB_est2 <- rbind(HD_NB.VP, HD_NB.VPtot, HD_NB.h2tot, HD_NB.h2)
HD_dist_est2 <- rbind(HD_dist.VP, HD_dist.VPtot, HD_dist.h2tot, HD_dist.h2)
HD_env_est2 <- rbind(HD_envir.VP, HD_envir.VPtot, HD_envir.h2tot, HD_envir.h2)


#output these 
HD_all_est <- cbind(HD_basic_est, HD_NB_est, HD_dist_est, HD_env_est)
write.csv(HD_all_est, file = './output/AnMod_estimates_varcomps_HD.csv')


HD_all_est2 <- cbind(HD_basic_est2, HD_NB_est2, HD_dist_est2, HD_env_est2)
write.csv(HD_all_est2, file = './output/AnMod_estimates_tots_HD.csv')





```